config/routes.rb
Rails.application.routes.draw do
 	
  root 'index#show'
  resources :cities
  # get 'gossips/new', to: 'gossips#new' #on affiche le formulaire
  # post 'gossips', to: 'gossips#create' #puis on l'envoie
  resources :gossips
  resources :users
  
  resources :gossips do
  resources :users
  end

  resources :comments

  resources :gossips do
  resources :comments
  resources :likes
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :tags, only: [:create]
  
  #get 'users/:id', to:'user#show', as: 'users'
  #get 'gossips/:id', to:'gossip#show', as: 'gossips'
  get 'welcome/:user_entry', to: 'welcome#show'
  get '/index', to: 'index#show'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show' 
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord

	validates :content,
		presence: true	
		
	belongs_to :user
	belongs_to :gossip
	#belongs_to :parent, polymorphic: true
	#has_many :comments, as: :parent
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title,
		presence: true,
		length: { in: 3..14 }

	validates :content,
		presence: true		

	belongs_to :user
	has_many :join_table_gossip_tags
	has_many :tags, through: :join_table_gossip_tags
	has_many :comments
	has_many :likes

	def pre_like(user)
    self.likes.find { |like| like.user_id == user.id}
    end
	
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip, optional: true
	belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_gossip_tags
	has_many :gossips, through: :join_table_gossip_tags

end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token


	validates :email, 
	    presence: true, 
	    uniqueness: true,
	    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Email adress please" }

	validates :password, 
		presence: true, length: { minimum: 6 }

	validates :first_name, 
		presence: true, length: { maximum: 50 }

	validates :last_name, 
		presence: true, length: { maximum: 50 }

	validates :age, 
		presence: true, numericality: { only_integer: true, greater_than: 0}
	
	validates :description, 
		length: { maximum: 500 }

	validates :city, 
		presence: true, allow_nil: false
 
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :gossips
  has_many :comments
  belongs_to :city
  has_many :likes
  has_secure_password



	def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end


	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	#return true si token match avec digest
	def authenticated?(remember_token)
	    return false if remember_digest.nil?
	    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  	end

	# oublier un user.
	def forget
		update_attribute(:remember_digest, nil)
	end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:create]
	def new
		@gossip = Gossip.all.find(params[:gossip_id])
		@comment = Comment.new
	end

	def create
		@gossip = Gossip.all.find(params[:gossip_id])
		@comment = Comment.create(content: post_params[:content], gossip: @gossip, user: current_user)
		puts "£" * 60
		puts post_params[:content]
		puts "£" * 60
		
  	
	  	if @comment.save
	  		flash[:success1] = " "
	  		redirect_to gossip_path(params[:gossip_id])
	  	else
	  		redirect_to gossip_path(params[:gossip_id])	
	  	end
	end

	def edit
		@comment = Comment.all.find(params[:id])
		@gossip = Gossip.all.find(params[:gossip_id])


	end

	def update
		@comment = Comment.find(params[:id])
		@gossip = Gossip.find(params[:gossip_id])

	    if @comment.update(content: params[:content], user: current_user)
	      flash[:success2] = " "
	      redirect_to gossip_path(params[:gossip_id])
	     else
	     render :edit 
    end
		
	end

	def destroy

		  @comment = Comment.all.find(params[:id])
		  @gossip = Gossip.find(params[:gossip_id])
	      @comment.destroy
	      
	       if flash[:success3] = " "
	      redirect_to gossip_path(params[:gossip_id])
	      else
	      render gossip_path(params[:gossip_id])
	  	end
		
	end


	private 

	def post_params

		params.require(:comment).permit(:content)
		
	end



  	def authenticate_user
	    unless current_user
	      flash[:danger] = "Please log in."
	      redirect_to new_session_path
	    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
  end

  def new
  end

  def create
    @tag = Tag.new(title: params[:title], content: params[:content], user: User.last) 
    if @gossip.save 
      flash[:success_tag] = "Votre tag a bien été enregistré !"
      redirect_to gossips_path
    else
      render new_gossip_path
    end
    
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

# Logs in the given user.
  	def log_in(user)
    session[:user_id] = user.id
  	end

# Remembers a user in a persistent session.
  	def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
  	end

# Returns the current logged-in user (if any).
	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		elsif cookies.signed[:user_id]
  			user = User.find_by(id: cookies.signed[:user_id])
  		
	  		if user && user.authenticated?(cookies[:remember_token])
	    		log_in user
	    		@current_user = user
	  		end
	  	end
  	end


  # Returns true if the user is logged in, false otherwise.
  	def logged_in?
    	!current_user.nil?
  	end


	# Forgets a persistent session.
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	
  	  # Logs out the current user.
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/edit.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>
  <body>



	<!-------------------------- ERROR MESSAGE -------------------------->



 
		<% if @comment.errors.any? %>
			<div class="alert alert-danger" role="alert">
	 			<p>Nous n'avons pas réussi à modifier le commentaire pour la (ou les) raison(s) suivante(s) :</p>
			
		  
		  		<ul>
		    		<% @comment.errors.full_messages.each do |message| %>
		     	 	<li><%= message %></li>
		    		<% end %>
		  		</ul>
		  	</div>
		<% end %> 



    <!-------------------------- CONTAINER -------------------------->

    <div class="container text-center">
    	</br>
	    </br>
	    </br>
	    </br>
	    <h1>ÉDITER TON COMMENTAIRE</h1>
	    </br>
	    </br>


		
		
		<%= form_tag url_for(action: 'update'), method: "put" do %>
		  <%= label_tag 'Contenu' %>
	      <%= text_area_tag 'content', '', class: "form-control", placeholder: "#{@comment.content}" %> 
	      <br/> <br/>



	      <%= submit_tag "Éditer mon commentaire", class: "btn btn-dark"%>
	      <%= link_to "Supprimer le commentaire", gossip_comment_path(@comment.gossip, @comment), class: "btn btn-danger", method: :delete, data: { confirm: 'Es-tu sûr de vouloir supprimer ce commentaire?' }%>

	    <% end %>
		 


	   
	    
	    </br>
	    </br>
	    </br>
	    <p> <%= link_to 'Retour à l\'Accueil', index_path %></p>

	</div>





    <!-------------------------- SCRIPT -------------------------->







    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>