config/routes.rb
Rails.application.routes.draw do
 	
  root 'index#show'
  resources :cities
  # get 'gossips/new', to: 'gossips#new' #on affiche le formulaire
  # post 'gossips', to: 'gossips#create' #puis on l'envoie
  resources :gossips
  resources :users
  
  resources :gossips do
  resources :users
  end

  resources :comments

  resources :gossips do
  resources :comments
  resources :likes
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :tags, only: [:create]
  
  #get 'users/:id', to:'user#show', as: 'users'
  #get 'gossips/:id', to:'gossip#show', as: 'gossips'
  get 'welcome/:user_entry', to: 'welcome#show'
  get '/index', to: 'index#show'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show' 
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord

	validates :content,
		presence: true	
		
	belongs_to :user
	belongs_to :gossip
	#belongs_to :parent, polymorphic: true
	#has_many :comments, as: :parent
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title,
		presence: true,
		length: { in: 3..14 }

	validates :content,
		presence: true		

	belongs_to :user
	has_many :join_table_gossip_tags
	has_many :tags, through: :join_table_gossip_tags
	has_many :comments
	has_many :likes

	def pre_like(user)
    self.likes.find { |like| like.user_id == user.id}
    end
	
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip, optional: true
	belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_gossip_tags
	has_many :gossips, through: :join_table_gossip_tags

end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token


	validates :email, 
	    presence: true, 
	    uniqueness: true,
	    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Email adress please" }

	validates :password, 
		presence: true, length: { minimum: 6 }

	validates :first_name, 
		presence: true, length: { maximum: 50 }

	validates :last_name, 
		presence: true, length: { maximum: 50 }

	validates :age, 
		presence: true, numericality: { only_integer: true, greater_than: 0}
	
	validates :description, 
		length: { maximum: 500 }

	validates :city, 
		presence: true, allow_nil: false
 
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :gossips
  has_many :comments
  belongs_to :city
  has_many :likes
  has_secure_password



	def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end


	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	#return true si token match avec digest
	def authenticated?(remember_token)
	    return false if remember_digest.nil?
	    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  	end

	# oublier un user.
	def forget
		update_attribute(:remember_digest, nil)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

# Logs in the given user.
  	def log_in(user)
    session[:user_id] = user.id
  	end

# Remembers a user in a persistent session.
  	def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
  	end

# Returns the current logged-in user (if any).
	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		elsif cookies.signed[:user_id]
  			user = User.find_by(id: cookies.signed[:user_id])
  		
	  		if user && user.authenticated?(cookies[:remember_token])
	    		log_in user
	    		@current_user = user
	  		end
	  	end
  	end


  # Returns true if the user is logged in, false otherwise.
  	def logged_in?
    	!current_user.nil?
  	end


	# Forgets a persistent session.
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	
  	  # Logs out the current user.
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/index/show.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>
  <body>


	<!-------------------------- SUCCESS MESSAGE -------------------------->


		<% if flash[:success] %>
			<div class="alert alert-success" role="alert">
	 			<p>Votre gossip à bien été enregistré ! </p>

		  	</div>
		<% end %> 


 
		<% if flash[:success1] %>
			<div class="alert alert-success" role="alert">
	 			<p>Votre gossip a bien été supprimé ! </p>

		  	</div>
		<% end %> 

		<% if flash[:success_user_signup] %>
			<div class="alert alert-success" role="alert">
	 			<p>Félicitations, vous êtes inscrits !</p>

		  	</div>
		<% end %>


	<!-------------------------- CONTAINER -------------------------->

	<div class="container justify-content-center">

		<div class="row text-center ">
			<div class="col-lg-12">
				<br>
				<br>
				<br>
				<br>
				<h1 class="text-center">BIENVENUE <br> SUR THE GOSSIP PROJECT</h1>
				<br/>
				<p>The Hacking Project est une chouette formation, où la communauté est reine. Il se passe plein de choses à Rennes, Paris, Lyon, Montpellier, Bordeaux et c'est dur de connaître tous les gossips. Samuel et Sarah ont créé une application où tout le monde peut ajouter des gossips sur ses camarades moussaillons. </p>
				<br/>
				<br/>
				<button class=" btn btn-outline-dark btn-outline-primary btn-lg"><%=link_to 'Créer un gossip', new_gossip_path %> </button>

				<br/>	
				<br/>
				<br/>
				<br/> 
				<br/>	
				<br/>
				<br/>
				<br/>
			</div>	
		</div>
		

		<div class="row justify-content-center">
			<div class="col-lg-6">
		<!-- Ici, on lui demande d'afficher pour chaque gossip, l'auteur + le contenu -->
				<% Gossip.all.each do |gossip| %>
					<div class="card text-center">
						<div class="card-header">
					  		<h3 class="card-title"><%=link_to gossip.title, gossip_path(gossip.id) %> </h3>
						</div>

					  	<div class="card-body">
					  		<p class="card-text"><%= gossip.user.first_name %></p>
					  	</div>
					  	<div>	
					  		<blockquote class="blockquote mb-0">
							  			<footer class="blockquote-footer text-right">
								  			<% gossip.tags.each do |tag|%>
													<p># <%= tag.title%> </p>
											<% end %>
										</footer>	
							</blockquote>
					     
						</div>	

			    	</div>
			    	<br>
			    	<br>
			    	<br>
			    	<br>
			    <% end %>

			</div>
		</div>

	</div>



	<!-------------------------- SCRIPT -------------------------->

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>






</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>




  <!-------------------------- NAV BAR -------------------------->




    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'The Gossip Project', index_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <%= link_to 'Accueil', index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Team', team_path, class: "nav-link" %> 
        </li>
        <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link" %>
      </ul>
        
        

      <ul class="navbar-nav my-2 my-lg-0">
      <% if !current_user%> 

        <li class="nav-item">
        <%=link_to 'Se connecter', new_session_path, class: "btn btn-outline-primary mr-2" %>
        </li>
        <br>
        <li class="nav-item">
        <%= link_to 'S\'inscrire', new_user_path, class: "btn btn-outline-primary mr-2" %>
        </li>

        <% else %>
        <li class="nav-item ">
        <%= link_to 'Mon compte', user_path(current_user.id), class: "nav-link btn mr-1" %>
        </li>

        <li class="nav-item ">
        <%= link_to 'Se déconnecter', session_path(session[:user_id]), method: :delete, data: {confirm: 'Êtes-vous sûr de vous déconnecter ?'}, class: "nav-link btn btn-outline-danger" %> 
        </li>
        
      <% end %>
      </ul>

        
    </div>

    </nav>



  <%= yield %>
  </body>
</html>