config/routes.rb
Rails.application.routes.draw do
 	
  root 'index#show'
  resources :cities
  # get 'gossips/new', to: 'gossips#new' #on affiche le formulaire
  # post 'gossips', to: 'gossips#create' #puis on l'envoie
  resources :gossips
  resources :users
  
  resources :gossips do
  resources :users
  end

  resources :comments

  resources :gossips do
  resources :comments
  resources :likes
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :tags, only: [:create]
  
  #get 'users/:id', to:'user#show', as: 'users'
  #get 'gossips/:id', to:'gossip#show', as: 'gossips'
  get 'welcome/:user_entry', to: 'welcome#show'
  get '/index', to: 'index#show'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show' 
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord

	validates :content,
		presence: true	
		
	belongs_to :user
	belongs_to :gossip
	#belongs_to :parent, polymorphic: true
	#has_many :comments, as: :parent
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title,
		presence: true,
		length: { in: 3..14 }

	validates :content,
		presence: true		

	belongs_to :user
	has_many :join_table_gossip_tags
	has_many :tags, through: :join_table_gossip_tags
	has_many :comments
	has_many :likes

	def pre_like(user)
    self.likes.find { |like| like.user_id == user.id}
    end
	
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip, optional: true
	belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_gossip_tags
	has_many :gossips, through: :join_table_gossip_tags

end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token


	validates :email, 
	    presence: true, 
	    uniqueness: true,
	    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Email adress please" }

	validates :password, 
		presence: true, length: { minimum: 6 }

	validates :first_name, 
		presence: true, length: { maximum: 50 }

	validates :last_name, 
		presence: true, length: { maximum: 50 }

	validates :age, 
		presence: true, numericality: { only_integer: true, greater_than: 0}
	
	validates :description, 
		length: { maximum: 500 }

	validates :city, 
		presence: true, allow_nil: false
 
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :gossips
  has_many :comments
  belongs_to :city
  has_many :likes
  has_secure_password



	def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end


	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	#return true si token match avec digest
	def authenticated?(remember_token)
	    return false if remember_digest.nil?
	    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  	end

	# oublier un user.
	def forget
		update_attribute(:remember_digest, nil)
	end


end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :show]

  def show
  	@id = params[:id]
    @gossip = Gossip.all.find(params[:id])
  	@comment = Comment.new
    @tags = Tag.all
  end


  def new
  	@gossip = Gossip.new
     @tags = Tag.all
  end



  def create
  	@gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)
    #tag = Tag.find(params[:tag])
    #@join_table_gossip_tag = JoinTableGossipTag.create(gossip: @gossip, tag: tag)
  	
  	if @gossip.save
  		flash[:success]
  		redirect_to index_path
  	else
  		render new_gossip_path	
  	end

  end

  def edit
      @id = params[:id]
      @gossip = Gossip.all.find(@id)
      @tags = Tag.all
  end


  def update
    @gossip = Gossip.find(params[:id])
    #tag = Tag.find(params[:tag])
    #join_table_gossip_tag = JoinTableGossipTag.where(gossip_id: @gossip.id)
    #join_table_gossip_tag.each do |join| join.update(gossip: @gossip, tag: tag)
    #end
    
    if @gossip.update(title: params[:title], content: params[:content], user: current_user)
      flash[:success] = "Ton gossip est bien modifié !"
      redirect_to gossip_path
     else
     render :edit 
    end
    
  end

  def destroy
     

      @gossip = Gossip.all.find(params[:id])
      @gossip.destroy
      
       if flash[:success1] = "Ton gossip a bien été supprimé !"
      redirect_to index_path
      else
      render gossip_path

      end
  end




  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end



end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
  end

  def new
  end

  def create
    @tag = Tag.new(title: params[:title], content: params[:content], user: User.last) 
    if @gossip.save 
      flash[:success_tag] = "Votre tag a bien été enregistré !"
      redirect_to gossips_path
    else
      render new_gossip_path
    end
    
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

# Logs in the given user.
  	def log_in(user)
    session[:user_id] = user.id
  	end

# Remembers a user in a persistent session.
  	def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
  	end

# Returns the current logged-in user (if any).
	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		elsif cookies.signed[:user_id]
  			user = User.find_by(id: cookies.signed[:user_id])
  		
	  		if user && user.authenticated?(cookies[:remember_token])
	    		log_in user
	    		@current_user = user
	  		end
	  	end
  	end


  # Returns true if the user is logged in, false otherwise.
  	def logged_in?
    	!current_user.nil?
  	end


	# Forgets a persistent session.
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	
  	  # Logs out the current user.
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>
  <body>



	<!-------------------------- ERROR MESSAGE -------------------------->



 
		<% if @gossip.errors.any? %>
			<div class="alert alert-danger" role="alert">
	 			<p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
			
		  
		  		<ul>
		    		<% @gossip.errors.full_messages.each do |message| %>
		     	 	<li><%= message %></li>
		    		<% end %>
		  		</ul>
		  	</div>
		<% end %> 



    <!-------------------------- CONTAINER -------------------------->

    <div class="container text-center">
    	</br>
	    </br>
	    </br>
	    </br>
	    <h1>ÉDITER LE GOSSIP : <%= "#{@gossip.title}" %></h1>
	    </br>
	    </br>


		
		
		<%= form_tag url_for(action: 'update'), method: "put" do %>

	      <%= label_tag 'Titre' %>
	      <%= text_field_tag 'title', '', class: "form-control", placeholder: "#{@gossip.title}" %>
	      <br/> <br/>

	      <%= label_tag 'Gossip' %>
	      <%= text_area_tag 'content', '', class: "form-control", placeholder: "#{@gossip.content}" %> 
	      <br/> <br/>



	      <%= submit_tag "Éditer mon post", class: "btn btn-dark" %>

	    <% end %>
		 


	   
	    
	    </br>
	    </br>
	    </br>
	    <p> <%= link_to 'Retour sur l\'accueil des gossips', index_path %></p>

	</div>





    <!-------------------------- SCRIPT -------------------------->







    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/gossips/new.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>
  <body>



	<!-------------------------- ERROR MESSAGE -------------------------->



 
		<% if @gossip.errors.any? %>
			<div class="alert alert-danger" role="alert">
	 			<p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
			
		  
		  		<ul>
		    		<% @gossip.errors.full_messages.each do |message| %>
		     	 	<li><%= message %></li>
		    		<% end %>
		  		</ul>
		  	</div>
		<% end %> 



    <!-------------------------- CONTAINER -------------------------->

    <div class="container text-center">
    	</br>
	    </br>
	    </br>
	    </br>
	    <h1>AJOUTER UN GOSSIP</h1>
	    </br>
	    </br>


		
		
		<%= form_tag url_for(action: 'create'), method: "post" do %>

	      <%= label_tag 'Titre' %>
	      <%= text_field_tag 'title', '', class: "form-control", placeholder:"Titre" %>
	      <br/> <br/>

	      <%= label_tag 'Gossip' %>
	      <%= text_area_tag 'content', '', class: "form-control", placeholder:"Gossip" %>
	      <br/> <br/>



	      <%= submit_tag "Créer mon post", class: "btn btn-dark" %>

	    <% end %>
		 


	   
	    
	    </br>
	    </br>
	    </br>
	    <p> <%= link_to 'Retour sur l\'accueil des gossips', index_path %></p>

	</div>





    <!-------------------------- SCRIPT -------------------------->







    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/gossips/show.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>
  <body>





<!-------------------------- ERROR MESSAGE -------------------------->


	<% if @comment.errors.any? %>
			<div class="alert alert-danger" role="alert">
	 			<p>Nous n'avons pas réussi à créer le commentaire pour la (ou les) raison(s) suivante(s) :</p>
			
		  
		  		<ul>
		    		<% @commentaire.errors.full_messages.each do |message| %>
		     	 	<li><%= message %></li>
		    		<% end %>
		  		</ul>
		  	</div>
		<% end %> 




	<!-------------------------- SUCCESS MESSAGE -------------------------->



 
		<% if flash[:success] %>
			<div class="alert alert-success" role="alert">
	 			<p>Votre gossip a bien été modifié ! </p>

		  	</div>
		<% end %> 

		<% if flash[:success1] %>
			<div class="alert alert-success" role="alert">
	 			<p>Votre commentaire a bien été créé ! </p>

		  	</div>
		<% end %> 

		<% if flash[:success2] %>
			<div class="alert alert-success" role="alert">
	 			<p>Votre commentaire a bien été modifié ! </p>

		  	</div>
		<% end %> 

		<% if flash[:success3] %>
			<div class="alert alert-success" role="alert">
	 			<p>Votre commentaire a bien été supprimé ! </p>

		  	</div>
		<% end %> 



  
    <!-------------------------- CONTAINER -------------------------->

    <div class="container text-center">
    	</br>
	    </br>
	    </br>
	    </br>
	    <h1>Voici la page du Gossip n°<%= @id%> </h1>
	    </br>
	    </br>

		<div class="card">
			<div class="card-body">
		  		<h3 class="card-title"><%= @gossip.title %></h3>
		  		<p class="card-text"><%= @gossip.content %></p>
		  		<blockquote class="blockquote mb-0">
		  			 <footer class="blockquote-footer text-right">
		  			 	<%= link_to "#{@gossip.user.first_name}", user_path(@gossip.user.id) %><br>
		  			 	<%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city) %> 

		  			 </footer></blockquote> 

		  			 
		  			 <% like = @gossip.pre_like(current_user)%>
                <% if like %>
                <%= link_to "Like #{@gossip.likes.count}", gossip_like_path(@gossip, like), method: :delete, class:"btn text-white btn-danger btn-sm"%>
                <% else %>
                <%= link_to "Like #{@gossip.likes.count}", gossip_likes_path(@gossip), method: :post, class:"btn text-red btn-light btn-sm"%>
                <% end %>



		  		<% if current_user == @gossip.user%>	 
		      	<button class=" btn btn-outline-dark btn-lg" role="button" aria-pressed="true"><%=link_to 'Éditer le gossip ?', edit_gossip_path %> </button>	
		      	
		      	<a href="<%= gossip_path(@gossip.id)%>" class=" btn btn-outline-danger btn-lg" role="button" aria-pressed="true" data-confirm="Êtes-vous sûr de supprimer le gossip ?" data-method ="DELETE"> Suprimer le gossip ? </a>
		      	<% end %>
		    </div>
    	</div>

	 


	   
	    
	    </br>
	    </br>
	    </br>


		<h3>COMMENTAIRES (<%= @gossip.comments.count %>)</h3>
			    </br>
			    </br>
			    <% @gossip.comments.each do |comment| %>
				 	<div class="card">
						<div class="card-body">
					  		<h3 class="card-title"><%=link_to "#{comment.user.first_name}", user_path(comment.user.id) %> </h3>
					  		<p class="card-text"><%= comment.content %></p>
					  		
					  		<% if current_user == comment.user%>
					  		<button class=" btn btn-outline-dark btn-lg"><%=link_to 'Éditer le commentaire', edit_gossip_comment_path(@gossip, comment) %> </button>
					  		<%end%>
					          	
					    </div>	
			    	</div> 
			    <% end %>
		</br>
	    </br>
	    </br>
	    </br>
	    <h4>AJOUTER UN COMMENTAIRE</h4>
	    </br>
	    </br>


		
		
		<%= form_for([@gossip, @comment]) do |form| %>
		<%= form.text_field :content, class: "form-control", placeholder:"Nouveau commentaire" %>
		<br>
		<%= form.submit "Ajouter", class: " btn btn-outline-dark btn-lg" %>
		<% end %>

	    </br>
	    </br>
	    </br>
	    <%= link_to 'Retour sur l\'accueil des gossips', index_path %>

	</div>





    <!-------------------------- SCRIPT -------------------------->







    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>